---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-demo
spec:
  selector:
    matchLabels:
      app: go-demo
  template:
    metadata:
      labels:
        app: go-demo
    spec:
      containers:
      - name: go-demo
        image: go-demo
        ports:
        - containerPort: 8080
        env:
        - name: CONFIG_VALUE
          valueFrom:
              configMapKeyRef:
                name: go-demo
                key: CONFIG_VALUE
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
