version: 2.1

jobs:
  test-clone:
    executor: 
    docker:
      - image: ubuntu
    steps:
    - run:
        command: |
          apt-get update
          apt-get install git -y
    - run:
        name: Git clone
        command: |
          #echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
          mkdir /root/.ssh
          touch /root/.ssh/known_hosts
          ssh-keyscan github.com >> /root/.ssh/known_hosts
          git clone git@github.com:etiennecoutaud/kubeusr.git


workflows:
   test:
      jobs:
        - test-clone

